{
    'name':'Lokesh',
    'favFoods':['Pizza','tacos','Salmon'],
    'age':31,
    'children':[
        {
            'name':'Zephyr',
            'age':4,
        },
        {
            'name':'Oliver',
            'age':5
        }
    ]
}